//! Code-security detector benchmark against the CyberSecEval Insecure Code
//! Detector corpus (Meta, MIT-licensed; vendored under
//! `benchmarks/datasets/inspect_evals/cyberseceval_4/`).
//!
//! Motivation: the survey "Large Language Models for Cyber Security" (Xu et
//! al., arXiv:2405.04760) reports that "over 50% of the code generated by LLMs
//! may contain vulnerabilities", yet `code_security.rs` shipped with unit tests
//! and **no corpus-level evaluation**. This example is that evaluation.
//!
//! Scope honesty: `CodeSecurityAnalyzer` targets seven web/app-layer
//! vulnerability classes. CyberSecEval spans the full CWE space (including C
//! memory-safety bugs the detector was never designed to catch). Scoring the
//! detector against out-of-scope CWEs would be misleading, so we measure
//! **recall on the intersection** of CyberSecEval CWEs and the detector's
//! taxonomy. Every sample in this corpus is known-vulnerable, so this measures
//! detection rate (recall); precision/FPR requires a benign-code corpus and is
//! a documented follow-up.
//!
//! Run:
//!   cargo run -p llmtrace-security --example code_security_cyberseceval
//!   cargo run -p llmtrace-security --example code_security_cyberseceval -- <path-to-instruct.json> [out.json]

use std::collections::BTreeMap;
use std::path::PathBuf;

use llmtrace_core::SecuritySeverity;
use llmtrace_security::code_security::CodeSecurityAnalyzer;
use serde::Deserialize;

/// Maps each in-scope CWE to the detector class (its `Display`) we expect to fire.
/// Only CWEs the detector is designed to catch are listed; everything else in
/// CyberSecEval is out of scope and excluded from the denominator.
const CWE_TO_CLASS: &[(&str, &str)] = &[
    ("CWE-78", "Command Injection"),          // OS command injection
    ("CWE-89", "SQL Injection"),              // SQL injection
    ("CWE-22", "Path Traversal"),             // path traversal
    ("CWE-798", "Hardcoded Credentials"),     // hardcoded credentials
    ("CWE-502", "Insecure Deserialization"),  // insecure deserialization
    ("CWE-79", "Cross-Site Scripting (XSS)"), // reflected/stored XSS
    ("CWE-327", "Insecure Cryptography"),     // broken/risky crypto algo
    ("CWE-328", "Insecure Cryptography"),     // reversible/weak hash
    ("CWE-338", "Insecure Cryptography"),     // weak PRNG for security
    ("CWE-330", "Insecure Cryptography"),     // insufficiently random values
];

#[derive(Debug, Deserialize)]
struct Record {
    #[serde(default)]
    cwe_identifier: String,
    #[serde(default)]
    language: String,
    #[serde(default)]
    origin_code: String,
}

/// Per-bucket tally: known-vulnerable samples, flagged at all, flagged with the
/// expected class.
#[derive(Default, Clone)]
struct Tally {
    total: usize,
    hit_any: usize,
    hit_class: usize,
}

impl Tally {
    fn record(&mut self, flagged_any: bool, flagged_class: bool) {
        self.total += 1;
        self.hit_any += usize::from(flagged_any);
        self.hit_class += usize::from(flagged_class);
    }
    fn recall_any(&self) -> f64 {
        pct(self.hit_any, self.total)
    }
    fn recall_class(&self) -> f64 {
        pct(self.hit_class, self.total)
    }
}

fn pct(num: usize, den: usize) -> f64 {
    if den == 0 {
        0.0
    } else {
        num as f64 / den as f64 * 100.0
    }
}

fn default_dataset_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../benchmarks/datasets/inspect_evals/cyberseceval_4/instruct.json")
}

/// Evaluate one analyzer config over the in-scope corpus, returning
/// (per-class, per-language, overall) tallies.
fn evaluate(
    analyzer: &CodeSecurityAnalyzer,
    records: &[Record],
) -> (BTreeMap<String, Tally>, BTreeMap<String, Tally>, Tally) {
    let class_for: BTreeMap<&str, &str> = CWE_TO_CLASS.iter().copied().collect();
    let mut by_class: BTreeMap<String, Tally> = BTreeMap::new();
    let mut by_lang: BTreeMap<String, Tally> = BTreeMap::new();
    let mut overall = Tally::default();

    for rec in records {
        let Some(&expected) = class_for.get(rec.cwe_identifier.as_str()) else {
            continue; // out-of-scope CWE
        };
        let text = format!("```{}\n{}\n```", rec.language, rec.origin_code);
        let findings = analyzer.analyze(&text);
        let flagged_any = !findings.is_empty();
        let flagged_class = findings
            .iter()
            .any(|f| f.metadata.get("vulnerability_type").map(String::as_str) == Some(expected));

        by_class
            .entry(expected.to_string())
            .or_default()
            .record(flagged_any, flagged_class);
        by_lang
            .entry(rec.language.clone())
            .or_default()
            .record(flagged_any, flagged_class);
        overall.record(flagged_any, flagged_class);
    }
    (by_class, by_lang, overall)
}

fn print_table(title: &str, rows: &BTreeMap<String, Tally>) {
    println!("\n{title}");
    println!(
        "| {:<28} | {:>7} | {:>10} | {:>12} |",
        "Bucket", "N", "Recall(any)", "Recall(class)"
    );
    println!("|{:-<30}|{:-<9}|{:-<12}|{:-<14}|", "", "", "", "");
    for (name, t) in rows {
        println!(
            "| {:<28} | {:>7} | {:>9.1}% | {:>11.1}% |",
            name,
            t.total,
            t.recall_any(),
            t.recall_class()
        );
    }
}

fn main() {
    let mut args = std::env::args().skip(1);
    let dataset = args
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(default_dataset_path);
    let out_path = args
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("benchmarks/results/code_security_cyberseceval.json"));

    let raw = match std::fs::read_to_string(&dataset) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "dataset not found at {} ({e}).\nVendor CyberSecEval4 first or pass a path argument.",
                dataset.display()
            );
            std::process::exit(2);
        }
    };
    let records: Vec<Record> = serde_json::from_str(&raw).expect("instruct.json is a JSON array");

    let in_scope = records
        .iter()
        .filter(|r| CWE_TO_CLASS.iter().any(|(c, _)| *c == r.cwe_identifier))
        .count();
    println!(
        "CyberSecEval Insecure-Code benchmark for code_security.rs\n\
         source: {}\n\
         total records: {}   in-scope (detector-relevant CWEs): {}",
        dataset.display(),
        records.len(),
        in_scope
    );

    // As-shipped (Medium threshold) is the headline; Low shows the ceiling.
    let configs = [
        ("as_shipped (>= Medium)", CodeSecurityAnalyzer::new()),
        (
            "sensitive (>= Low)",
            CodeSecurityAnalyzer::with_severity_threshold(SecuritySeverity::Low),
        ),
    ];

    let mut report = serde_json::Map::new();
    report.insert("dataset".into(), dataset.display().to_string().into());
    report.insert("total_records".into(), records.len().into());
    report.insert("in_scope".into(), in_scope.into());

    for (name, analyzer) in &configs {
        let (by_class, by_lang, overall) = evaluate(analyzer, &records);
        println!("\n========== config: {name} ==========");
        println!(
            "OVERALL  N={}  recall(any)={:.1}%  recall(class)={:.1}%",
            overall.total,
            overall.recall_any(),
            overall.recall_class()
        );
        print_table("By vulnerability class:", &by_class);
        print_table("By language:", &by_lang);

        let cfg = serde_json::json!({
            "overall": {
                "n": overall.total,
                "recall_any_pct": overall.recall_any(),
                "recall_class_pct": overall.recall_class(),
            },
            "by_class": by_class.iter().map(|(k, t)| (k.clone(), serde_json::json!({
                "n": t.total, "recall_any_pct": t.recall_any(), "recall_class_pct": t.recall_class(),
            }))).collect::<serde_json::Map<_, _>>(),
            "by_language": by_lang.iter().map(|(k, t)| (k.clone(), serde_json::json!({
                "n": t.total, "recall_any_pct": t.recall_any(), "recall_class_pct": t.recall_class(),
            }))).collect::<serde_json::Map<_, _>>(),
        });
        report.insert((*name).to_string(), cfg);
    }

    report.insert(
        "note".into(),
        "Recall on known-vulnerable LLM-relevant code (CyberSecEval). \
         Precision/FPR requires a benign-code corpus (follow-up)."
            .into(),
    );

    if let Some(parent) = out_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(&out_path, serde_json::to_string_pretty(&report).unwrap()) {
        Ok(()) => println!("\nwrote {}", out_path.display()),
        Err(e) => eprintln!("\nfailed to write {}: {e}", out_path.display()),
    }
}
